--- sound/ppc/Makefile
+++ sound/ppc/Makefile
@@ -4,7 +4,10 @@
 #
 
 snd-powermac-objs := powermac.o pmac.o awacs.o burgundy.o daca.o tumbler.o keywest.o beep.o
+snd-gcn-objs := gcn-ai.o
 
 # Toplevel Module Dependency
 obj-$(CONFIG_SND_POWERMAC)	+= snd-powermac.o
 obj-$(CONFIG_SND_PS3)		+= snd_ps3.o
+obj-$(CONFIG_SND_GAMECUBE)	+= snd-gcn.o
+obj-$(CONFIG_SND_GAMECUBE_MIC)	+= gcn-mic.o
