--- mm/Makefile
+++ mm/Makefile
@@ -6,7 +6,7 @@ KASAN_SANITIZE_slab_common.o := n
 KASAN_SANITIZE_slub.o := n
 
 mmu-y			:= nommu.o
-mmu-$(CONFIG_MMU)	:= gup.o highmem.o memory.o mincore.o \
+mmu-$(CONFIG_MMU)	:= gup.o memory.o mincore.o \
 			   mlock.o mmap.o mprotect.o mremap.o msync.o rmap.o \
 			   vmalloc.o pagewalk.o pgtable-generic.o
 
